before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: fcFc6GKy5dqjNqh/WikE6i22R4U5Afx1z5rFQD2f5YQHOTGawZ141/J9gGtgE9f0vf110pKdJP4UTJIRaUVS7G1pUliSgYkENMJn99hzByC7iY+z7bTl7lwKMN1mg3YDtuk1DAx2R6FJfsradzOD4Kyt0n3Co/Le+wfwXpOA3j/Qm2O0CFHVsBAnP6WVh7i8XL+ZXFbSS8jAzruCdt/FH5zpWnnvlUy0d229z/cyNzzdXdzZikhm3NmEkI+Uv+XNPq9H+z6mwsPLaIvGGlP+O9UOnU0CYP6LqOfE1SmAU7fbqshV2otN5KxLWHNBcRAly20D17Z1S5FsxKCS4Nr8hd4M+e7K/9RPncZkmhhqZlbalRupA7oniRkSLWCEhYoxsXvxNNeWxupSbEj3+nc6G4a4+INNvSCDHMUBtRqYJdJ+RHMFQwRdew6hiDD46loE6kFU4GhwubR5KS+qsQEhmWYS15E6NwLLDYAtMhZJEHs+8Q8SsuFPBljHesc/lBEhEJvErC67dJJCAIcmDw+Y+LZgqREowinFGeiIaWjdnsOvtTe3Wk4mvzsQLz2rL+4eg2M1XyOlOtXSGDydBBeMiWi5MF6NdlaF2PjX2fZSiVKwdon+iCIBwx1LuDbG5LUzaR47fw11gAfgNNrh5hMZCHmc/Rl83Tgf2EKj1EWW/4I= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
